version: 2

defaults: &defaults
    parallelism: 1
    working_directory: /tmp/cv-rollbar
    environment:
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

jobs:
  build:
    <<: *defaults
    docker:
      - image: fpco/stack-build
    steps:
    - checkout

    - run:
        name: Initialize workspace
        command: mkdir -p workspace
    - run:
        name: Initialize artifact storage
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    - restore_cache:
        keys:
        - cv-rollbar-cache-v2-dep-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "rollbar.cabal" }}
        # This branch if available
        - cv-rollbar-cache-v2-dep-{{ .Branch }}-
        # Default branch if not
        - cv-rollbar-cache-v2-dep-master-
        # Any branch if there are none on the default branch -
        # this should be unnecessary if you have your default branch
        # configured correctly
        - cv-rollbar-cache-v2-dep-
    - run:
        name: Build binary
        command: stack build --install-ghc --pedantic --ghc-options="-O2"

    # Save dependency cache
    - save_cache:
        key: cv-rollbar-cache-v2-dep-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "rollbar.cabal" }}
        paths:
        - ~/.stack
        - .stack-work

    # Test
    - run:
        name: Run tests
        command: stack test --no-terminal --coverage
    - run:
        name: Copy coverage reports
        command: cp -r $(stack path --local-hpc-root) $CIRCLE_ARTIFACTS

    # Documentation
    - run:
        name: Generate documentation
        command: make docs && cp -r $(stack path --local-doc-root) $CIRCLE_ARTIFACTS

    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results

    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
